# Generated by Django 2.2.3 on 2019-07-29 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190214_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceip', models.CharField(max_length=45)),
                ('macaddress', models.CharField(max_length=45)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=45)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=80, null=True)),
                ('lastaccessed', models.DateTimeField(null=True)),
                ('penaltycount', models.IntegerField(default=0, null=True)),
                ('rulenum', models.IntegerField(default=0, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.AddField(
            model_name='audit',
            name='blacklistid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Blacklist'),
        ),
    ]
