# Generated by Django 2.2.3 on 2019-11-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191126_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipaddress', models.CharField(max_length=45)),
                ('domain', models.CharField(default='', max_length=500)),
                ('port', models.IntegerField(default=80, null=True)),
            ],
        ),
    ]
