# Generated by Django 2.2.3 on 2019-11-26 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
