# Generated by Django 2.2.3 on 2019-11-26 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_auto_20191126_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('sourceip', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('macaddress', models.CharField(max_length=45)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipaddress', models.CharField(max_length=45)),
                ('domain', models.CharField(default='', max_length=500)),
                ('port', models.IntegerField(default=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastaccessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('penaltycount', models.IntegerField(default=0, null=True)),
                ('rulenum', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=45)),
                ('ipaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Blacklist')),
            ],
        ),
    ]
