# Generated by Django 2.2.3 on 2019-11-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_audit_blacklist_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
