# Generated by Django 2.2.3 on 2019-11-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191126_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='port',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
    ]
