# Generated by Django 2.2.3 on 2019-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_audit_penalty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='sourceip',
            field=models.CharField(max_length=45),
        ),
    ]
