# Generated by Django 2.2.3 on 2019-11-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191126_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
