# Generated by Django 2.2.3 on 2019-11-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_blacklist_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='ipaddress',
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
