# Generated by Django 2.2.3 on 2019-11-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_audit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
