# Generated by Django 2.2.3 on 2019-11-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_audit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penalty',
            old_name='ipaddress',
            new_name='id_blacklist',
        ),
    ]
