# Generated by Django 2.2.3 on 2019-12-11 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20191211_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sourceip', models.CharField(max_length=45)),
                ('macaddress', models.CharField(max_length=45)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastaccessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('penaltycount', models.IntegerField(default=0, null=True)),
                ('rulenum', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=45)),
                ('id_blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Blacklist')),
            ],
        ),
    ]
